
   1 #! /usr/bin/env python
   2 #  -*- coding: utf-8 -*-
   3 #
   4 # GUI module generated by PAGE version 4.18
   5 #  in conjunction with Tcl version 8.6
   6 #    Nov 13, 2018 10:03:26 PM CET  platform: Windows NT
   7 
   8 import sys
   9 
  10 try:
  11     import Tkinter as tk
  12 except ImportError:
  13     import tkinter as tk
  14 
  15 try:
  16     import ttk
  17     py3 = False
  18 except ImportError:
  19     import tkinter.ttk as ttk
  20     py3 = True
  21 
  22 import _support
  23 
  24 def vp_start_gui():
  25     '''Starting point when module is the main routine.'''
  26     global val, w, root
  27     root = tk.Tk()
  28     top = Toplevel1 (root)
  29     _support.init(root, top)
  30     root.mainloop()
  31 
  32 w = None
  33 def create_Toplevel1(root, *args, **kwargs):
  34     '''Starting point when module is imported by another program.'''
  35     global w, w_win, rt
  36     rt = root
  37     w = tk.Toplevel (root)
  38     top = Toplevel1 (w)
  39     _support.init(w, top, *args, **kwargs)
  40     return (w, top)
  41 
  42 def destroy_Toplevel1():
  43     global w
  44     w.destroy()
  45     w = None
  46 
  47 class Toplevel1:
  48     def __init__(self, top=None):
  49         '''This class configures and populates the toplevel window.
  50            top is the toplevel containing window.'''
  51         _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
  52         _fgcolor = '#000000'  # X11 color: 'black'
  53         _compcolor = '#d9d9d9' # X11 color: 'gray85'
  54         _ana1color = '#d9d9d9' # X11 color: 'gray85' 
  55         _ana2color = '#d9d9d9' # X11 color: 'gray85' 
  56 
  57         top.geometry("600x450+462+291")
  58         top.title("New Toplevel")
  59         top.configure(background="#d9d9d9")
  60 
  61         self.Frame1 = tk.Frame(top)
  62         self.Frame1.place(relx=0.033, rely=0.044, relheight=0.611
  63                 , relwidth=0.192)
  64         self.Frame1.configure(relief='groove')
  65         self.Frame1.configure(borderwidth="2")
  66         self.Frame1.configure(relief='groove')
  67         self.Frame1.configure(background="#d9d9d9")
  68         self.Frame1.configure(width=115)
  69 
  70         self.Button1 = tk.Button(self.Frame1)
  71         self.Button1.place(relx=0.174, rely=0.055, height=42, width=68)
  72         self.Button1.configure(activebackground="#d9d9d9")
  73         self.Button1.configure(activeforeground="#000000")
  74         self.Button1.configure(background="#d9d9d9")
  75         self.Button1.configure(disabledforeground="#a3a3a3")
  76         self.Button1.configure(foreground="#000000")
  77         self.Button1.configure(highlightbackground="#d9d9d9")
  78         self.Button1.configure(highlightcolor="black")
  79         self.Button1.configure(pady="0")
  80         self.Button1.configure(text='''Button''')
  81 
  82         self.Button1_1 = tk.Button(self.Frame1)
  83         self.Button1_1.place(relx=0.174, rely=0.291, height=42, width=68)
  84         self.Button1_1.configure(activebackground="#d9d9d9")
  85         self.Button1_1.configure(activeforeground="#000000")
  86         self.Button1_1.configure(background="#d9d9d9")
  87         self.Button1_1.configure(disabledforeground="#a3a3a3")
  88         self.Button1_1.configure(foreground="#000000")
  89         self.Button1_1.configure(highlightbackground="#d9d9d9")
  90         self.Button1_1.configure(highlightcolor="black")
  91         self.Button1_1.configure(pady="0")
  92         self.Button1_1.configure(text='''Button''')
  93 
  94         self.Button1_2 = tk.Button(self.Frame1)
  95         self.Button1_2.place(relx=0.174, rely=0.509, height=42, width=68)
  96         self.Button1_2.configure(activebackground="#d9d9d9")
  97         self.Button1_2.configure(activeforeground="#000000")
  98         self.Button1_2.configure(background="#d9d9d9")
  99         self.Button1_2.configure(disabledforeground="#a3a3a3")
 100         self.Button1_2.configure(foreground="#000000")
 101         self.Button1_2.configure(highlightbackground="#d9d9d9")
 102         self.Button1_2.configure(highlightcolor="black")
 103         self.Button1_2.configure(pady="0")
 104         self.Button1_2.configure(text='''Button''')
 105 
 106         self.Button1_3 = tk.Button(self.Frame1)
 107         self.Button1_3.place(relx=0.174, rely=0.727, height=42, width=68)
 108         self.Button1_3.configure(activebackground="#d9d9d9")
 109         self.Button1_3.configure(activeforeground="#000000")
 110         self.Button1_3.configure(background="#d9d9d9")
 111         self.Button1_3.configure(disabledforeground="#a3a3a3")
 112         self.Button1_3.configure(foreground="#000000")
 113         self.Button1_3.configure(highlightbackground="#d9d9d9")
 114         self.Button1_3.configure(highlightcolor="black")
 115         self.Button1_3.configure(pady="0")
 116         self.Button1_3.configure(text='''Button''')
 117 
 118         self.Frame2 = tk.Frame(top)
 119         self.Frame2.place(relx=0.233, rely=0.044, relheight=0.611
 120                 , relwidth=0.725)
 121         self.Frame2.configure(relief='groove')
 122         self.Frame2.configure(borderwidth="2")
 123         self.Frame2.configure(relief='groove')
 124         self.Frame2.configure(background="#d9d9d9")
 125         self.Frame2.configure(width=435)
 126 
 127 if __name__ == '__main__':
 128     vp_start_gui()
 129 
 130 


